#!/bin/bash

if [ ! -d bin ]; then
    mkdir bin
    cp config.xml.skel bin/config.xml
fi

scalac -classpath lib/pircbot.jar -sourcepath src/main/scala -d bin src/main/scala/de/sammyshp/announcebot/AnnounceBot.scala

